/**
 * FysiSteps Eco Marketplace Product Service
 * Multi-vendor, categorized sustainable products catalog.
 */

async function getProducts() {
  return [
    // ══════════════════ 1. PLANTS & NATURE ══════════════════
    {
      id: "prod_plant_01",
      title: "Neem Tree Sapling with Organic Root Ball",
      name: "Neem Tree Sapling with Organic Root Ball",
      category: "plants",
      vendor: "EarthRoot Botanicals",
      price: 249,
      originalPrice: 399,
      rating: 4.8,
      reviewsCount: 380,
      ecoCoinsReward: 35,
      badge: "Air Purifier",
      ecoImpact: "Absorbs ~22kg CO₂/year when mature; natural bio-pest repellent.",
      image: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=600&q=80",
      description: "Hardy native Indian neem sapling grown in biodegradable coir pot. Perfect for home gardens or community planting."
    },
    {
      id: "prod_plant_02",
      title: "Organic Rama & Krishna Tulsi Dual Pot",
      name: "Organic Rama & Krishna Tulsi Dual Pot",
      category: "plants",
      vendor: "Vriksha Nursery",
      price: 189,
      originalPrice: 299,
      rating: 4.9,
      reviewsCount: 620,
      ecoCoinsReward: 25,
      badge: "Herb of Grace",
      ecoImpact: "Releases oxygen up to 20 hours daily; natural immunity booster.",
      image: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=600&q=80",
      description: "Sacred Tulsi duo grown without chemical pesticides. Comes in a 100% natural terracotta breathable planter."
    },
    {
      id: "prod_plant_03",
      title: "Snake Plant (Sansevieria) in Terracotta Pot",
      name: "Snake Plant (Sansevieria) in Terracotta Pot",
      category: "plants",
      vendor: "GreenHaven Flora",
      price: 349,
      originalPrice: 499,
      rating: 4.8,
      reviewsCount: 410,
      ecoCoinsReward: 40,
      badge: "NASA Top Air-Filter",
      ecoImpact: "Removes airborne toxins including formaldehyde and benzene.",
      image: "https://images.unsplash.com/photo-1599598425947-5202edd564c5?auto=format&fit=crop&w=600&q=80",
      description: "Low-maintenance indoor plant requiring minimal watering. Enhances bedroom air quality with nocturnal oxygen release."
    },
    {
      id: "prod_plant_04",
      title: "Native Butterfly & Bee Wildflower Seed Kit",
      name: "Native Butterfly & Bee Wildflower Seed Kit",
      category: "plants",
      vendor: "EarthRoot Botanicals",
      price: 199,
      originalPrice: 299,
      rating: 4.7,
      reviewsCount: 235,
      ecoCoinsReward: 30,
      badge: "Pollinator Friendly",
      ecoImpact: "Creates vibrant local pollinator corridors supporting biodiversity.",
      image: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=600&q=80",
      description: "Non-GMO heirloom seeds of Indian marigold, zinnia, cosmos, and sunflowers. Complete with coco-peat germination disks."
    },

    // ══════════════════ 2. SUSTAINABLE CLOTHING ══════════════════
    {
      id: "prod_cloth_01",
      title: "Handloom Khadi & Organic Cotton Casual Kurta",
      name: "Handloom Khadi & Organic Cotton Casual Kurta",
      category: "clothing",
      vendor: "GreenWeave Handlooms",
      price: 799,
      originalPrice: 1299,
      rating: 4.9,
      reviewsCount: 310,
      ecoCoinsReward: 75,
      badge: "100% Hand-Spun",
      ecoImpact: "Zero electricity weaving; uses 65% less water than industrial denim/cotton.",
      image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80",
      description: "Breathable natural dyed khadi kurta. Naturally thermal-regulating, keeps you cool in summer and warm in winter."
    },
    {
      id: "prod_cloth_02",
      title: "Pure Hemp Fabric Overshirt (Unisex)",
      name: "Pure Hemp Fabric Overshirt (Unisex)",
      category: "clothing",
      vendor: "Prakriti Textiles",
      price: 999,
      originalPrice: 1599,
      rating: 4.8,
      reviewsCount: 195,
      ecoCoinsReward: 90,
      badge: "Zero Pesticide",
      ecoImpact: "Hemp sequesters 4x more carbon per hectare than commercial pine forests.",
      image: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80",
      description: "Durable, anti-microbial industrial hemp overshirt. Softens with each wash and lasts up to 3x longer than cotton."
    },
    {
      id: "prod_cloth_03",
      title: "GOTS-Certified Organic Cotton Everyday Tee",
      name: "GOTS-Certified Organic Cotton Everyday Tee",
      category: "clothing",
      vendor: "GreenWeave Handlooms",
      price: 499,
      originalPrice: 799,
      rating: 4.8,
      reviewsCount: 440,
      ecoCoinsReward: 45,
      badge: "GOTS Certified",
      ecoImpact: "Zero synthetic pesticides used; printed using safe water-based inks.",
      image: "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=600&q=80",
      description: "Ultra-soft 180 GSM ring-spun organic cotton crew-neck t-shirt. Naturally breathable and biodegradable."
    },

    // ══════════════════ 3. ECO-FRIENDLY BAGS ══════════════════
    {
      id: "prod_bag_01",
      title: "Heavy-Duty Golden Jute Shopping Tote",
      name: "Heavy-Duty Golden Jute Shopping Tote",
      category: "bags",
      vendor: "EcoJute Craft Co.",
      price: 249,
      originalPrice: 399,
      rating: 4.9,
      reviewsCount: 880,
      ecoCoinsReward: 30,
      badge: "Plastic Replacement",
      ecoImpact: "Replaces over 500 single-use thin poly bags in its lifespan.",
      image: "https://images.unsplash.com/photo-1597633425046-08f5110420b5?auto=format&fit=crop&w=600&q=80",
      description: "Reinforced woven natural jute bag with padded cotton handles. Can carry up to 18kg of groceries with ease."
    },
    {
      id: "prod_bag_02",
      title: "Unbleached Canvas Market Shopper (Pack of 2)",
      name: "Unbleached Canvas Market Shopper (Pack of 2)",
      category: "bags",
      vendor: "PureBags India",
      price: 349,
      originalPrice: 549,
      rating: 4.8,
      reviewsCount: 520,
      ecoCoinsReward: 40,
      badge: "Washable & Reusable",
      ecoImpact: "100% compostable cotton fibers; completely plastic and chemical-bleach free.",
      image: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=600&q=80",
      description: "Set of 2 unbleached natural canvas tote bags with inner zippered pocket for keys and wallet. Machine washable."
    },
    {
      id: "prod_bag_03",
      title: "Cotton Mesh Produce Fridge Bags (Pack of 6)",
      name: "Cotton Mesh Produce Fridge Bags (Pack of 6)",
      category: "bags",
      vendor: "EcoJute Craft Co.",
      price: 299,
      originalPrice: 449,
      rating: 4.7,
      reviewsCount: 360,
      ecoCoinsReward: 35,
      badge: "Zero Plastic Pantry",
      ecoImpact: "Keeps vegetables crisp without trapping moisture inside plastic wraps.",
      image: "https://images.unsplash.com/photo-1610444583716-953e5e40639d?auto=format&fit=crop&w=600&q=80",
      description: "Breathable organic cotton mesh bags in 3 convenient sizes (S, M, L) with drawstrings. Tare weight tags included."
    },

    // ══════════════════ 4. BAMBOO PRODUCTS ══════════════════
    {
      id: "prod_bamboo_01",
      title: "Organic Charcoal Bamboo Toothbrush Family Pack (4-Pack)",
      name: "Organic Charcoal Bamboo Toothbrush Family Pack (4-Pack)",
      category: "bamboo",
      vendor: "BambooVibe Living",
      price: 199,
      originalPrice: 349,
      rating: 4.9,
      reviewsCount: 1240,
      ecoCoinsReward: 25,
      badge: "100% Biodegradable Handle",
      ecoImpact: "Diverts 4 plastic toothbrushes that take 450+ years to decompose.",
      image: "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?auto=format&fit=crop&w=600&q=80",
      description: "Ergonomic Moso bamboo handle with activated charcoal-infused soft bristles for gentle and effective plaque removal."
    },
    {
      id: "prod_bamboo_02",
      title: "Handcrafted Bamboo Desktop Organizer & Stand",
      name: "Handcrafted Bamboo Desktop Organizer & Stand",
      category: "bamboo",
      vendor: "EcoDesk Creations",
      price: 499,
      originalPrice: 799,
      rating: 4.8,
      reviewsCount: 290,
      ecoCoinsReward: 50,
      badge: "Sustainable Craft",
      ecoImpact: "Rapidly renewable bamboo harvested without destroying parent root system.",
      image: "https://images.unsplash.com/photo-1591129841117-3adfd313e34f?auto=format&fit=crop&w=600&q=80",
      description: "Multi-compartment organizer for stationery, phone, and cables made from seasoned natural bamboo with water-resistant finish."
    },
    {
      id: "prod_bamboo_03",
      title: "5-Piece Bamboo Kitchen Cooking Utensil Set",
      name: "5-Piece Bamboo Kitchen Cooking Utensil Set",
      category: "bamboo",
      vendor: "BambooVibe Living",
      price: 399,
      originalPrice: 599,
      rating: 4.8,
      reviewsCount: 460,
      ecoCoinsReward: 40,
      badge: "Naturally Antibacterial",
      ecoImpact: "Non-toxic alternative to melamine or Teflon-coated plastic cooking ladles.",
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80",
      description: "Set includes spatula, slotted spoon, solid spoon, pasta server, and turner. Safe for non-stick cookware and non-scratching."
    },
    {
      id: "prod_bamboo_04",
      title: "Portable Bamboo Cutlery Travel Kit with Pouch",
      name: "Portable Bamboo Cutlery Travel Kit with Pouch",
      category: "bamboo",
      vendor: "BambooVibe Living",
      price: 249,
      originalPrice: 399,
      rating: 4.7,
      reviewsCount: 380,
      ecoCoinsReward: 30,
      badge: "Zero-Waste Travel",
      ecoImpact: "Eliminates disposable plastic forks, spoons, and straws on road trips.",
      image: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=600&q=80",
      description: "Fork, spoon, knife, chopsticks, bamboo straw, and cleaner in a roll-up washable canvas pouch."
    },

    // ══════════════════ 5. OTHER SUSTAINABLE PRODUCTS ══════════════════
    {
      id: "prod_other_01",
      title: "Double-Walled Insulated Stainless Steel Bottle (750ml)",
      name: "Double-Walled Insulated Stainless Steel Bottle (750ml)",
      category: "other",
      vendor: "PureTerra Essentials",
      price: 599,
      originalPrice: 999,
      rating: 4.9,
      reviewsCount: 940,
      ecoCoinsReward: 60,
      badge: "Lifetime Reusable",
      ecoImpact: "Replaces ~180 single-use PET plastic beverage bottles annually.",
      image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80",
      description: "Food-grade 304 stainless steel with vacuum insulation keeping water cold for 24h or hot for 12h. Leak-proof bamboo cap."
    },
    {
      id: "prod_other_02",
      title: "100% Plant-Based Compostable Trash Bags (Pack of 30)",
      name: "100% Plant-Based Compostable Trash Bags (Pack of 30)",
      category: "other",
      vendor: "BioShield Packs",
      price: 249,
      originalPrice: 349,
      rating: 4.8,
      reviewsCount: 510,
      ecoCoinsReward: 30,
      badge: "ISO 17088 Certified",
      ecoImpact: "Composts in home soil within 90-180 days; zero microplastic residue.",
      image: "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=600&q=80",
      description: "Made from cornstarch and PBAT. Certified biodegradable under municipal composting standards for green kitchen waste."
    },
    {
      id: "prod_other_03",
      title: "Plantable Seed Paper Journal & Seed Pen Duo",
      name: "Plantable Seed Paper Journal & Seed Pen Duo",
      category: "other",
      vendor: "Kagaz Kala",
      price: 299,
      originalPrice: 449,
      rating: 4.9,
      reviewsCount: 370,
      ecoCoinsReward: 35,
      badge: "Zero-Waste Stationery",
      ecoImpact: "Cover and pen cap contain basil and tomato seeds that grow when buried.",
      image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80",
      description: "100 pages of recycled cotton-rag wood-free paper. Once used, plant the cover in a pot to bloom fresh herbs."
    },
    {
      id: "prod_other_04",
      title: "Handcrafted Coconut Shell Scented Soy Candle",
      name: "Handcrafted Coconut Shell Scented Soy Candle",
      category: "other",
      vendor: "PureTerra Essentials",
      price: 349,
      originalPrice: 499,
      rating: 4.8,
      reviewsCount: 280,
      ecoCoinsReward: 35,
      badge: "Upcycled Waste",
      ecoImpact: "Upcycles discarded temple/kitchen coconut shells into elegant decor.",
      image: "https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=600&q=80",
      description: "Poured with pure soy wax and sandalwood essential oil in a reclaimed polished coconut bowl with wooden crackling wick."
    }
  ];
}

module.exports = {
  getProducts
};
